### ISSUE TITLE
Retry logic for external api call failures

### ISSUE THREAD

**Issue by second-string** [dot4qu/Show-Finder#21]
```
/Users/brianteam/Developer/Show-Finder/node_modules/async-request/src/main.js:24
                    throw new Error(error);
                    ^

Error: Error: getaddrinfo ENOTFOUND rest.bandsintown.com rest.bandsintown.com:443
    at Request.request [as _callback] (/Users/brianteam/Developer/Show-Finder/node_modules/async-request/src/main.js:24:27)
    at self.callback (/Users/brianteam/Developer/Show-Finder/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.onRequestError (/Users/brianteam/Developer/Show-Finder/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:188:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)```

**Comment by second-string** [comment]
haha fuck
https://github.com/gajus/async-request/issues/15

**Comment by second-string** [comment]
No retry logic but gracefully handling failure with switch to node-fetch since it doesn't throw within itself for failures
